apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-wordpress
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# service
