apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pv-claim-wordpress
      namespace: ns-common-resources
      labels:
        app: wordpress
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pv-claim-mysql
      namespace: ns-common-resources
      labels:
        app: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi   

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      namespace: ns-common-resources
      name: pv-claim-nextcloud
      labels:
        app: nextcloud
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi