apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-wordpress
      namespace: ns-common-resources
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "$ENV_REPO_PATH/data/data-wordpress"

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-mysql
      namespace: ns-common-resources
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "$ENV_REPO_PATH/data/data-mysql"
    #  persistentVolumeReclaimPolicy: Retain

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: pv-nextcloud
      namespace: ns-common-resources
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 1Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        # REPO_PATH
        path: "$ENV_REPO_PATH/data/data-nextcloud"
    #  persistentVolumeReclaimPolicy: Retain